---
- name: Развертывание веб-сервера Apache с системной информацией
  hosts: all
  become: yes
  gather_facts: yes
  
  roles:
    - apache_setup
  
  tasks:
    - name: Проверить доступность веб-сайта
      uri:
        url: "http://{{ ansible_default_ipv4.address }}/"
        status_code: 200
        timeout: 30
      register: website_check
      until: website_check.status == 200
      retries: 5
      delay: 10
      changed_when: false
    
    - name: Вывести результат проверки
      debug:
        msg: "Веб-сайт доступен! HTTP статус: {{ website_check.status }}"
      when: website_check.status == 200